---
name: Setup build
description: Setup the OS-independent build environment
inputs:
  setup-go:
    description: Enable Go setup
    type: boolean
    required: false
    default: true
  setup-node:
    description: Enable Node setup
    type: boolean
    required: false
    default: true
  node-version:
    description: Node version to install
    type: number
    required: false
    default: 18
  go-version:
    description: Go version to install
    type: string
    required: false
    default: 'stable'
runs:
  using: composite
  steps:
    # Setup
    - uses: actions/setup-go@v4
      if: ${{ inputs.setup-go == 'true' }}
      id: go-setup
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
    - uses: actions/setup-node@v3
      if: ${{ inputs.setup-node == 'true' }}
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: console/frontend/package-lock.json
