---
name: Setup build
description: Setup the OS-independent build environment
inputs:
  setup-go:
    description: Enable Go setup
    type: boolean
    required: false
    default: true
  setup-node:
    description: Enable Node setup
    type: boolean
    required: false
    default: true
  node-version:
    description: Node version to install
    type: number
    required: false
    default: 20
  go-version:
    description: Go version to install
    type: string
    required: false
    default: '1.24'
runs:
  using: composite
  steps:
    # Setup
    - uses: actions/setup-go@v5
      if: ${{ inputs.setup-go == 'true' }}
      id: go-setup
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: true
    - uses: actions/setup-node@v4
      if: ${{ inputs.setup-node == 'true' }}
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: console/frontend/package-lock.json
    - uses: actions/cache/restore@v4
      with:
        path: |
          orchestrator/clickhouse/data/udp.csv
          orchestrator/clickhouse/data/tcp.csv
        key: cache-iana-${{ hashFiles('Makefile', 'nix/ianaServiceNamesHash.txt') }}-${{ github.run_id }}
        restore-keys: |
          cache-iana-${{ hashFiles('Makefile', 'nix/ianaServiceNamesHash.txt') }}-
