#!/bin/sh

# Generate definition_gen.go from definition.go.

set -e

cat <<EOF
// Code generated by definition_gen.sh. DO NOT EDIT.

package schema

import "akvorado/common/helpers/bimap"

var columnNameMap = bimap.New(map[ColumnKey]string{
$(grep -oEw 'Column[a-zA-Z0-9]+' common/schema/definition.go \
    | sed 's/^Column//' \
    | grep -vFx Last \
    | grep -vFx Key \
    | sort | uniq \
    | awk '{ print "Column"$1": \""$1"\","}')
})
EOF
