---
# List of licenses compatible with AGPL-3.0-only
allowlist:
  - Apache-2.0
  - BSD-3-Clause
  - BSD-2-Clause
  - BSD-2-Clause-Views
  - MPL-2.0
  - MIT
  - ISC
  - WTFPL
  - 0BSD

exceptions:
  - github.com/pascaldekloe/name # CC0, not detected
