apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipinfo-geoip-shared-pv
  namespace: {{ .Values.environment }}-{{ .Values.namespace }}
spec:
  storageClassName: "standard"
  capacity:
    {{- if and (.Values.volumes) (.Values.volumes.ipinfo_geoip_data_shared) (.Values.volumes.ipinfo_geoip_data_shared.storageSize)}}
    storage: {{ .Values.volumes.ipinfo_geoip_data_shared.storageSize }}
    {{- else }}
    storage: 100Mi
    {{- end }}
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: {{ .Values.environment }}-{{ .Values.namespace }}
    name: ipinfo-geoip-shared-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: {{ .Values.volumes.ipinfo_geoip_data_shared.volumeHandle }}
    fsType: ext4
    readOnly: true