apiVersion: v1
kind: Service
metadata:
  name: inlet-http
  namespace: {{ .Values.environment }}-{{ .Values.namespace }}
  labels:
    app: inlet-http
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: inlet