---
name: Feature request
description: Request a new feature
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Disclaimer
      description: |
        For support questions, please use the [discussions][] instead. Before
        requesting a feature, check it does not already exist in the
        [documentation][]. You are quite welcome opening a feature request
        before spending time to implement it yourself.

        [documentation]: https://demo.akvorado.net/docs/intro
        [discussions]: https://github.com/akvorado/akvorado/discussions
      options:
        - label: I have read and understood the above paragraph.
          required: true
        - label: I plan to implement the feature myself.
  - type: input
    attributes:
      label: Akvorado version
      description: |
        Provide the Akvorado version (first line of `akvorado version` or
        `docker compose run --rm akvorado-inlet version`)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature description
      description: |
        Provide a description of the feature you request. When using code
        snippets (logs, commands), put them between triple backticks:

        ````
        ```
        # akvorado version | head -2
        akvorado v1.11.2
          Built with: go1.23.2 X:loopvar
        ```
        ````
    validations:
      required: true
