FROM gcr.io/distroless/static:latest
LABEL org.opencontainers.image.source=https://github.com/akvorado/akvorado
LABEL org.opencontainers.image.description="Akvorado: flow collector, enricher and visualizer (dev)"
LABEL org.opencontainers.image.licenses=AGPL-3.0-only
COPY bin/akvorado /usr/local/bin/
EXPOSE 8080
HEALTHCHECK CMD [ "/usr/local/bin/akvorado", "healthcheck" ]
ENTRYPOINT [ "/usr/local/bin/akvorado" ]
