---
# This configuration file is documented in docs/50-configuration.md.
#
# You can get all default values with:
#
#   akvorado orchestrator /dev/null --dump --check
#
# or
#
#   docker compose run --rm --no-deps akvorado-orchestrator orchestrator /dev/null --dump --check
#
# Do not use the output of the command as your configuration file, it should
# only help you get the default values.

kafka:
  topic: flows
  brokers:
    - kafka:9092
  topic-configuration:
    num-partitions: 8
    replication-factor: 1
    config-entries:
      # The retention policy in Kafka is mainly here to keep a buffer
      # for ClickHouse.
      segment.bytes: 1073741824
      retention.ms: 86400000 # 1 day
      cleanup.policy: delete
      compression.type: producer

clickhousedb:
  servers:
    - clickhouse:9000

clickhouse:
  orchestrator-url: http://akvorado-orchestrator:8080
  prometheus-endpoint: /metrics
  asns:
    64501: ACME Corporation

inlet: !include "inlet.yaml"
outlet: !include "outlet.yaml"
console: !include "console.yaml"