---
snmp:
  name: th2-edge2.example.com
  interfaces:
    10: "Transit: Cogent"
    11: "IX: DECIX"
    20: "core"
    21: "core"
  listen: :161
bmp: !include "demo-bmp.yaml"
flows: !include "demo-flows.yaml"
