---
snmp:
  name: dc3-edge1.example.com
  interfaces:
    10: "Transit: Tata"
    11: "Transit: Lumen"
    20: "core"
    21: "core"
  listen: :161
bmp: !include "demo-bmp.yaml"
flows: !include "demo-flows.yaml"
