-- Schema generated by gorm + glebarez/sqlite (v1.11.0) for the SavedFilter model.
-- Used to test backward compatibility of the bun-based code with existing
-- databases created by the previous gorm-based implementation.
CREATE TABLE `saved_filters` (`id` integer PRIMARY KEY AUTOINCREMENT,`user` text,`shared` numeric,`description` text,`content` text);
CREATE INDEX `idx_saved_filters_user` ON `saved_filters`(`user`);
INSERT INTO `saved_filters` VALUES(1, '__system', 1, 'From Netflix', 'InIfBoundary = external AND SrcAS = AS2906');
INSERT INTO `saved_filters` VALUES(2, '__system', 1, 'From GAFAM', 'InIfBoundary = external AND SrcAS IN (AS15169, AS16509, AS32934, AS6185, AS8075)');
INSERT INTO `saved_filters` VALUES(144, 'alfred', 1, 'From Free', 'InIfBoundary = external AND SrcAS = AS12322');
