---
name: Update PGO profile
on:
  workflow_dispatch:
  schedule:
    - cron: "26 8 1 * *"

jobs:
  pgo:
    name: Update PGO profile
    runs-on: ubuntu-latest
    if: github.repository_owner == 'akvorado'
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Download profile
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          rm -f default.pgo
          run_id=$(gh run list --workflow ci.yml --branch main --status success \
                               --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run download "$run_id" --name pgo --dir .
      - name: Set up git identity
        uses: ./.github/actions/identity
        with:
          client-id: ${{ secrets.AKVORADO_APP_ID }}
          private-key: ${{ secrets.AKVORADO_APP_KEY }}
      - name: Push update
        run: |
          git add default.pgo
          ! git commit -m "build: update PGO profile" || git push
