---
name: Update Nix dependency hashes
on:
  workflow_dispatch:
  schedule:
    - cron: "46 3 * * *"

jobs:
  hashes:
    name: Update dependency hashes
    runs-on: ubuntu-latest
    if: github.repository_owner == 'akvorado'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0        # All history needed
      - name: Check for changes
        id: check-changes
        if: github.event_name == 'schedule'
        run: |
          LOCKFILES="go.sum console/frontend/pnpm-lock.yaml"
          LAST_CHANGE=$(git log -1 --format=%ct -- $LOCKFILES)
          CURRENT_TIME=$(date +%s)
          ONE_HOUR_AGO=$((CURRENT_TIME - 3600))
          LONG_TIME_AGO=$((CURRENT_TIME - 181440))
          echo "Last change was $(( (CURRENT_TIME - LAST_CHANGE) / 60 )) minutes ago"
          if [ "$LAST_CHANGE" -gt "$LONG_TIME_AGO" ] && [ "$LAST_CHANGE" -le "$ONE_HOUR_AGO" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
        if: github.event_name != 'schedule' || steps.check-changes.outputs.should_run == 'true'
      - name: Update dependency hashes
        if: github.event_name != 'schedule' || steps.check-changes.outputs.should_run == 'true'
        run: nix run .#update
      - name: Set up git identity
        if: github.event_name != 'schedule' || steps.check-changes.outputs.should_run == 'true'
        uses: ./.github/actions/identity
        with:
          client-id: ${{ secrets.AKVORADO_APP_ID }}
          private-key: ${{ secrets.AKVORADO_APP_KEY }}
      - name: Push update
        if: github.event_name != 'schedule' || steps.check-changes.outputs.should_run == 'true'
        run: |
          git add flake.lock nix
          ! git commit -m "build: update Nix dependency hashes" || git push
